### ISSUE TITLE
Only one non-steam game shortcut shows up in Rainway at a time.

### ISSUE THREAD

**Issue by BetaLeaf** [RainwayApp/bug-tracker#254]
### Steps to trigger the problem that are specific, and repeatable
Add 2 or more non-steam games to steam as shortcuts then go to https://play.rainway.io and refresh the list of games.
#### Expected:
All non-steam games should show up.
#### Reality:
Only the first game shows up. The game that shows up is determined by the shortcuts.vdf file.
```"C:\Program Files (x86)\Steam\userdata\<SteamID>\config\shortcuts.vdf"```
### Did this work in a previous version? If so, also provide the version that it worked in.
I'm not 100% sure, but I think I've had this bug since the very beginning, when the open beta was launched.
### OS version
Windows 10 Pro Version 1803 Build 17134.228
### Extensions? Any browser extensions you might have installed.
Not Applicable due to server-side issue.
`Lastpass: Free Password Manager`, `Rebrandly`, `Application Launcher for Drive (by Google)`
### Any errors logged in your Server.log file?
You can view my full log at [ServerLog.7z](https://cdn.discordapp.com/attachments/359715202989686785/490356121765281812/ServerLog.7z)
In particular, these lines stood out to me:
```
2018-09-14 22:53:56,233 [23] WARN Rainway.Core.Games.AnalyzerService - Found Pokemon Trading Card Game Online(59e1227013373b06f42a808929602f0e) via SteamShortcut
2018-09-14 22:53:57,198 [26] WARN Rainway.Core.Games.Analyzers.SteamShortcutAnalyzer - Skipping Remote Desktop because it's already added
2018-09-14 22:53:57,200 [26] WARN Rainway.Core.Games.Analyzers.SteamShortcutAnalyzer - Skipping Console because it's already added
2018-09-14 22:53:57,202 [26] WARN Rainway.Core.Games.Analyzers.SteamShortcutAnalyzer - Skipping Launchbox because it's already added
```
### Was the error on a client/app or the server?
Server
### Additional Notes
I have cleared cache via the tray icon several times.
I have done a clean reinstall of Rainway. 
I have deleted and allowed steam to recreate the `Shortcuts.vdf` file.
I have tried Force Analyser Refresh in the tray icon.

**Comment by healingbrew** [comment]
Does the shortcuts.vdf file have more than one shortcut?

**Comment by BetaLeaf** [comment]
Yes it does. It has 4 entries:
Pokemon Trading Card Game Online
Remote Desktop
Console
Launchbox

[shortcuts.zip](https://github.com/RainwayApp/bug-tracker/files/2394090/shortcuts.zip)

**Comment by healingbrew** [comment]
Will be fixed in the next update.

**Comment by BetaLeaf** [comment]
Thanks, Naomi. When does the next update launch? (rough eta is fine)

**Comment by JTTM** [comment]
@BetaLeaf 
![screenshot_20180919-155525](https://user-images.githubusercontent.com/14990787/45791312-d6991000-bc24-11e8-991e-b32d41a86388.png)

**Comment by BetaLeaf** [comment]
Thanks @JTTM 
Wonder what the bug was. An issue in parsing the Shortcuts.vdf?

**Comment by Codeusa** [comment]
I used regular expressions to parse binary. @healingbrew has properly scolded me.

**Comment by BetaLeaf** [comment]
Sure, you got scolded, but at least you came out of it and learned something from it. Anyways, glad the issue was fixed. Have a good day.

**Comment by healingbrew** [comment]
Actually the issue was a "filter" we implemented to strip out "weird" characters from a name, but at some point it broke and removed _all_ characters.

I rewrote the VDF parser from regex to a more sane parser to have some maintainability, which is a seperate concern.

**Comment by BetaLeaf** [comment]
Confirmed fixed. Thanks.

**Comment by alekseyruzh** [comment]
@healingbrew have added our non-steam indie game project as a shortcut to steam, the name is Encoder.exe, have also changed an icon inside the steam itself, still does not show up in my play.rainway.io

can you please help?

**Comment by BetaLeaf** [comment]
This is not the same issue. Please open a new issue with as much info and
things you have tried as you can.

**Comment by JTTM** [comment]
@alekseyruzh Please join the Discord https://rain.gg/discord for more help with this issue.
