### ISSUE TITLE
Chromebook WebRTC Connection Failed

### ISSUE THREAD

**Issue by joecasanova** [RainwayApp/bug-tracker#270]
ChromeOS version 71.0.3578.127 (Official Build) (64-bit)

Attempting to connect to play.rainway.com results in "WebRTC Connection Failed".  This connection has a desktop running Rainway and another desktop running the latest build of Chrome on Windows 10 Pro had no issue connecting to the gaming desktop to stream games.  Android phones also have the same issue on this network (and via 4G cellular).

Please advise.

**Comment by JTTM** [comment]
It would be best to report issues on the Discord right now. Thanks.

https://rain.gg/discord

**Comment by Hopalonger** [comment]
I am having the Exact Same Problem On a Chromebook It was working for a bit and now there is just the WebRTC Connection Failed.

**Comment by fcmanj** [comment]
I am also having this issue , though im on windows10.

**Comment by JakubFojtik** [comment]
Also having this issue, only Opera client works, Chrome and Chromium get that error.
Edit: Opera stopped working as well... Tried both Windows and Linux clients.

Is there a way to debug this? I tried HTTPS Decrypt MITM in Fiddler but that caused Connection lost.
My NAT type is Full Cone at both ends.
Also tried disabling firewall server-side.

**Comment by andrewmd5** [comment]
Connection issues over the last few days were caused by hardware outages on our infrastructure. Those were resolved as of last night and you need to restart Rainway.

**Comment by JakubFojtik** [comment]
> Connection issues over the last few days were caused by hardware outages on our infrastructure. Those were resolved as of last night and you need to restart Rainway.

I was trying it today for the first time, fresh install. I restarted Rainway at least 3 times in the process too. As of now it still does not work. And those people before wrote months ago.

Teamviewer works fine, but is slow and choppy. I'm sad because when Rainway worked for me it worked great (for the hour or so), unlike TW.

**Comment by andrewmd5** [comment]
WebRTC not working can be caused by a number of things:
- You might have a browser extension blocking it. Try running Chrome in Incognito and disabling any browser extensions to see if you can connect.
- You might need to port forward ([see here](https://rainway.com/support/unabletoconnect/))
- There could be an issue still with your Dashboard not registering properly. If you delete the Rainway folder from AppData this will reset it.

**Comment by JakubFojtik** [comment]
It started working for me again, what i did was boot the Windows host physically instead of running it in a VM. But now it works in the VM as well. Maybe just needed a reboot; strange.
Not sure how related this is to other people's issues in this thread though.
