### ISSUE TITLE
Installation succeeds, but Rainway silently fails to launch

### ISSUE THREAD

**Issue by sakshamgoyal01** [RainwayApp/bug-tracker#272]
I installed it but when i click the icon, nothing happens. no rainway related processes are running in task manager. when installing, there is a splash screen for installing, then nothing. 

windows 10 home
rainway 1.0.3.0

**Comment by SimoFoto** [comment]
I have the same issue. I get the UAC admin privilege pop-up, when launching, bet afterwards - nothing.

**Comment by sakshamgoyal01** [comment]
[SquirrelSetup.log](https://github.com/RainwayApp/bug-tracker/files/2826473/SquirrelSetup.log)
installer log file

**Comment by Wolframme** [comment]
Looked in the issue tracker for it, and I am indeed getting the exact same issue.

**Comment by JTTM** [comment]
Hello! Thank you for reporting this! This has already been reported to the devs and is being fixed. 

Also, it would be best to report issues on the Discord for right now.
https://rain.gg/discord

**Comment by sakshamgoyal01** [comment]
v1.0.4.0 and it still wont work.

**Comment by UlyssesWu** [comment]
Same here with v1.0.4.0. 
v1.0.3.0 could launch.

**Comment by sakshamgoyal01** [comment]
1.0.6.0 doesn't work either.

**Comment by Codeusa** [comment]
Have you verified its just not in your tray icon? Could you attach logs if its not running still?

**Comment by UlyssesWu** [comment]
v1.0.6.0 works for me. 

Although I always get a "Network Error" when trying to sign in. (from v1.0.3.0 to v1.0.6.0)

**Comment by sakshamgoyal01** [comment]
no error. no warning. nothing. it's completely silent. and no tray icon either. this is a new computer so i dont understand why this is happening.

**Comment by sakshamgoyal01** [comment]
i have indexed my whole pc, searched for rainway, deleted all of it, re-installed, problem persists.

**Comment by AnthonyM** [comment]
@sakshamgoyal01 I'm trying to track this down. Would you be able to give the logs from
C:\Users\<your username>\Local\Rainway, Inc\Launcher\Launcher.log
and
C:\Users\<your username>\Local\Rainway, Inc\Installer\Installer.log

and if you give me your computer name I can check if we're seeing any exceptions coming through on our end. 

Thanks

**Comment by sakshamgoyal01** [comment]
my computer: lenovo y7000p. it may be under the name of y530 (the y7000 is a y530 rebranded). 

i dont have a launcher.log
my installer.log:
2019-02-12 20:06:48,051 [1] ERROR InstallTool.Program - Installer Method Timing
System.Exception: Not an exception
2019-02-13 16:32:55,312 [1] ERROR InstallTool.Program - Installer Method Timing
System.Exception: Not an exception

**Comment by Codeusa** [comment]
@sakshamgoyal01 When we say computer name, we mean the name that appears under "Control Panel\System and Security\System"

![image](https://user-images.githubusercontent.com/1297077/52761103-f27fc280-2fc6-11e9-8e87-7eb7196c9214.png)

Sorry for the confusion.

**Comment by sakshamgoyal01** [comment]
name: Saksham-lenovo
it is exactly as above.

i only have windows defender installed. it is not blocking the installation (from what i could tell). idk how to turn it off

**Comment by AnthonyM** [comment]
There are a couple other things we can try to narrow the problem down, if you don't mind. 

First thing would be to make sure the Radar service is actually working

```
start menu -> search for "cmd" -> right click command prompt and choose run as admin
"net start RainwayRadar"
```
That should tell you if the service started successfully.

**Comment by sakshamgoyal01** [comment]
![image](https://user-images.githubusercontent.com/19929553/52821000-2e706180-3073-11e9-8331-43413b2816ba.png)

**Comment by AnthonyM** [comment]
Okay, so the service isn't able to start. 

Are you by any chance running 32 bit windows? You can check by the steps below. 

```
start menu -> search for "cmd" -> right click command prompt and choose run as admin
"wmic os get osarchitecture"
```

**Comment by sakshamgoyal01** [comment]
nope... 64 bit. i thought windows 10 doesnt support 32bit.

**Comment by sakshamgoyal01** [comment]
![image](https://user-images.githubusercontent.com/19929553/52908091-f82e1000-3233-11e9-9216-89ac361c491b.png)

**Comment by TicklesTheBrain** [comment]
It actually launches for me fine on 1.0.6.0 So whatever my problem was with 1.0.3.0 and 1.0.4.0. its different from what saksham is encountering.

**Comment by AnthonyM** [comment]
@TicklesTheBrain I made some changes to help with this in 1.0.6.0

If it's working well for you that's good. 

@sakshamgoyal01 There is still 32 bit windows 10, it's just not very common. That was apparently one possible cause. I'm still trying to figure out what else might be causing that error.

**Comment by sakshamgoyal01** [comment]
any update?

**Comment by portalpiggy** [comment]
Having the same problem on Rainway V1.0.6

**Comment by sakshamgoyal01** [comment]
any update.

**Comment by sakshamgoyal01** [comment]
still waiting for a fix

**Comment by sakshamgoyal01** [comment]
still waiting....

**Comment by sakshamgoyal01** [comment]
1.0.7 doesnt work

**Comment by sakshamgoyal01** [comment]
please change the label of this issue to 1.0.7
this needs to be fixed.

**Comment by StackDoubleFlow** [comment]
Still waiting for this one

**Comment by lynn** [comment]
Hey! Our developers are still investigating this issue, but it remains elusive. There have been a few patches to the installer since we first got reports on this issue, but sadly enough – despite our efforts – it still seems present in the latest version. So we'll keep at it.

We promise we'll let you know once we find out what's up with this!

**Comment by naldo29** [comment]
hey im having this issue, does anyone know how to actually fix it?

**Comment by sakshamgoyal01** [comment]
nope. still waiting.

**Comment by Codeusa** [comment]
@sakshamgoyal01 After installing Rainway, do this.

Control Panel->Administration->Services->Right Clicked Rainway Radar->Properties->Log On, switch to "This account", enter your username/password for Windows, and click OK.

![](https://i.imgur.com/XiwPqj3.png)

Now try running Rainway and see if it works.

**Comment by sakshamgoyal01** [comment]
![image](https://user-images.githubusercontent.com/19929553/55678007-0b666f00-58b8-11e9-8b0c-14b5af139c08.png)

**Comment by Codeusa** [comment]
@sakshamgoyal01 

can you try doing the following

- Uninstall Rainway
- Delete everything in C:\Users{Your Windows Name}\AppData\Local\Rainway and then the folder "Rainway" itself
- Open powershell and type "Remove-Service -Name RainwayRadar"
- Reinstall Rainway

Also after installing, go to the services page and right click on "Rainway Radar" and click properties, and copy and paste the "path to executable" here, and also verify the file exist where it thinks it is

**Comment by sakshamgoyal01** [comment]
path to exe:

"C:\Users\Saksham Goyal\AppData\Local\Rainway\Radar\Radar.exe"  -displayname "Rainway Radar" -servicename "RainwayRadar"

still doesnt work. when i uninstalled rainway, the service went away so i coundnt do the powershell thingy

**Comment by sakshamgoyal01** [comment]
when rainway is installed, I get this error in powershell when trying to remove the service while it is installed:
![image](https://user-images.githubusercontent.com/19929553/55688753-f6ceb900-5941-11e9-8dac-36d9f226f06c.png)

**Comment by MattCastellana** [comment]
I had this exact issue and was able to get it working by first uninstalling rainway, and then deleting the RainwayRadar service using command prompt (Running as Administrator). 

I used these commands:

> SC STOP RainwayRadar

And then:

> SC DELETE RainwayRadar

Then I reinstalled rainway and it worked perfectly!   I think the issue happened originally due to the fact I tried installing a new version of rainway over top of my existing version, possibly while the service was still running.   Not sure if that's exactly what caused it, but I think next time I'll update via the app if possible.

**Comment by portalpiggy** [comment]
I've just tried all of these suggestions, but the problem still persists...

**Comment by sakshamgoyal01** [comment]
![image](https://user-images.githubusercontent.com/19929553/55765712-9cfbeb00-5a36-11e9-9934-144e97c4a83c.png)

**Comment by portalpiggy** [comment]
same exact thing happened to me

**Comment by sakshamgoyal01** [comment]
1.0.9.0 fixed it for me. 
this too a while but got fixed in the end.

**Comment by lynn** [comment]
Hey all, @TicklesTheBrain @Wolframme @UlyssesWu @portalpiggy @StackDoubleFlow!

We pushed out version 1.0.9.0 on [rainway.com](https://rainway.com/), which should fix this issue.

Please let us know if it works for you now :)

**Comment by portalpiggy** [comment]
Sorry it's been a while but it still doesn't work with 1.0.11 for me...

**Comment by NektariosEvangelou** [comment]
Problem still on 1.0.17, service not able to start manually. Did all of the steps above and still no signs of life...

**Comment by sakgoyal** [comment]
well it works for me now....

**Comment by Official-Pepsi** [comment]
I seem to be having the same problem as the Sakshamgoyal01 guy, just now it's with the lastest version of Rainway. Followed all the steps there and all the same problems happened

**Comment by lynn** [comment]
Hey @Official-Pepsi, we're releasing a brand new installer very soon and hopefully all these issues should go away with it!  So I'll close this issue for now, and I hope you try again when we release the next version of the Dashboard (should be sometime next month for sure).

**Comment by andrewmd5** [comment]
Hey everyone, this issue has been resolved. If you run [this tool](https://nexus.rainway.com/janitor.exe) then Rainway should install.

**Comment by 29axe** [comment]
Hi, I have the exact same issue with 1.0.54. I tried to start service and it gives me the 1067 error too. 
I ran janitor tool and reinstalled but still the same issue. 
I'm trying to install Rainway using remote desktop without having the display turned on. Could it be related?

**Comment by ayvah** [comment]
@29axe 
I'm experiencing the same issue, also using Remote Desktop. So yes, it seems related. I wonder if there's a work around that doesn't involve permanently having a monitor attached?

**Comment by 29axe** [comment]
@ayvah Exactly. When try without remote desktop it works. As an alternative I could start rainway using teamviewer.
